
app {
    name: "Spark Warehouse Project"
}

spark {
    master: "local[*]"
}


database { 
    host: ${POSTGRES_HOST} 
    port: ${POSTGRES_PORT} 
    name: ${POSTGRES_DB} 
    user: ${POSTGRES_USER} 
    password: ${POSTGRES_PASSWORD} 
    driver: "org.postgresql.Driver" 
}

paths {
    cust_info: "data/source_crm/cust_info.csv"
    prod_info: "data/source_crm/prd_info.csv"
    sales_details: "data/source_crm/sales_details.csv"
    loc_a101: "data/source_erp/loc_a101.csv"
    cust_az12: "data/source_erp/cust_az12.csv"
    px_cat_g1v2: "data/source_erp/px_cat_g1v2.csv"
}




